apiVersion: v1
kind: Service
metadata:
  name: my-bucks-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008 # Fixed port for easy access
  selector:
    app: my-bucks