apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: myflix-container
        image: g3niuz/myflix:36ee2e23355b3c4858580df22dc3860ec2acf8e8
        ports:
        - containerPort: 80
        # ADD THIS BLOCK BELOW:
        resources:
          requests:
            cpu: "100m"   # 10% of a vCPU
            memory: "128Mi"
          limits:
            cpu: "200m"   # Cap it at 20% so it doesn't kill the node
            memory: "256Mi"
